In [16]:
import numpy as np

In [17]:
def multiclass_perceptron (X,Y,lr,n_iter):
    labels = set(Y)
    n_labels = len(labels) # k
    n_features = X.shape[1]
    weights = []
    w_steps = []

    for i in range(n_labels):
        weights.append(np.zeros(n_features))
    weights = np.array(weights)

    for i in range(n_iter):
        for j in range(len(Y)):
            print('----------------------------------------------------------------------------------------------------------')
            print('Itteration number : '+ str(j+1) + ' at epoch :'+str(i+1))
            xt = X[j]
            yt = Y[j]
            print('Xt is :', xt)
            print('Yt is :', yt+1)
            predictions = weights.dot(xt)
            print('Y-predected is the max out of this array : ', predictions)
            y_pred = np.argmax(predictions)
            print('Y-predected is : ', y_pred+1)
            if yt != y_pred :
                print('yt and y-pred are not equal !!!')
                for w in range(n_labels):
                    if yt == w:
                        weights[w] = weights[w] + lr*xt
                        print('Wt new is : ',weights[w])
                    else:
                        weights[w] = weights[w] - lr*xt
            w_steps.append(np.copy(weights))
            print('Weights after this itteration :')
            print(weights)
    return weights, w_steps

In [18]:
def delta(Wi,Wt,Xt):
    if (1 + (Wi.dot(Xt) - Wt.dot(Xt))) > 0:
        return 1
    else:
        return 0

In [19]:
def multiclass_SVM (X,Y,lr,n_iter):
    labels = set(Y)
    n_labels = len(labels) # k
    n_features = X.shape[1]
    weights = []
    w_steps = []

    for i in range(n_labels):
        weights.append(np.zeros(n_features))
    weights = np.array(weights)

    for i in range(n_iter):
        for j in range(len(Y)):
            print('----------------------------------------------------------------------------------------------------------')
            print('Itteration number : '+ str(j+1) + ' at epoch :'+str(i+1))
            xt = X[j]
            yt = Y[j]
            print('Xt is :', xt)
            print('Yt is :', yt+1)
            for w in range(n_labels):
                if yt == w:
                    deltas = []
                    for wj in range(n_labels):
                        if wj == yt:
                            continue
                        deltas.append(delta(weights[wj],weights[yt],xt))
                    print('all deltas to change Wt :')
                    print(deltas)
                    weights[w] = weights[w] + lr * xt * np.sum(deltas)
                    print('Wt new is : ' , weights[w])
                else:
                    print('The delta of W '+ str(w+1) +' is : ', delta(weights[w], weights[yt], xt))
                    weights[w] = weights[w] - lr * xt * delta(weights[w], weights[yt], xt)
          
                  
            w_steps.append(np.copy(weights))
            print('Weights after this itteration :')
            print(weights)
    return weights, w_steps

In [20]:
def softmax(Xt,W,Yi):
    expA = np.exp(W[Yi].dot(Xt))
    expB = sum(np.exp(W[i].dot(Xt)) for i in range(len(W)))
    return expA/expB 

In [52]:
def multiclass_multinomial_logisticR(X,Y,lr,n_iter):
    labels = set(Y)
    n_labels = len(labels) # k
    n_features = X.shape[1]
    weights = []
    w_steps = []

    for i in range(n_labels):
        weights.append(np.zeros(n_features))
    weights = np.array(weights)

    for i in range(n_iter):
        for j in range(len(Y)):
            print('----------------------------------------------------------------------------------------------------------')
            print('Itteration number : '+ str(j+1) + ' at epoch :'+str(i+1))
            xt = X[j]
            yt = Y[j]
            print('Xt is :', xt)
            print('Yt is :', yt+1)
            y_pred = softmax(xt,weights,yt)
            print('(Y predected) Value is :', y_pred)
            print('(1 - Y predected) Value is :', 1 - y_pred)
            for w in range(n_labels):
                if yt == w:
                    print('this is w ' + str(w+1))
                    gradient = y_pred * xt
                else:
                    print('this is w '+ str(w+1))
                    gradient = -(1-y_pred) * xt
                print('grad = ',gradient)
                weights[w] = weights[w] + lr * gradient
            w_steps.append(np.copy(weights))
            print('Weights after this itteration :')
            print(weights)
    return weights, w_steps


# Normalize Vector

In [84]:
def normalize_Vector(X):
    NormVector = []
    for i in range(X.shape[1]):
        print('------------------------------------------------------------------------------------')
        print(X[:,i])
        mean = np.mean(X[:,i])
        print('Mean of the vector is : ', mean)
        std  = np.std(X[:,i])
        print('STD of the vector is : ', std)
        z=[]
        for j in range(len(X[:,i])):
            z.append((X[j,i]-mean)/std)
        NormVector.append(z)
        
    return NormVector

def realNormalized(NormVector,OriginalArray):
    arr = np.zeros(OriginalArray.shape)
    for i in range(NormVector.shape[0]):
        for j in range(NormVector.shape[1]):
            arr[j][i] = NormVector[i][j] 
    return arr

In [23]:
Vector = np.array([[0,0,1],[0,1,1],[1,0,1],[2,0,1],[2,1,1],[3,0,1],[0,3,1],[0,4,1],[1,3,1]])
print('------------------------------------------------------------------------------------')
print(normalize_Vector(Vector))

------------------------------------------------------------------------------------
[0 0 1 2 2 3 0 0 1]
------------------------------------------------------------------------------------
Mean of the vector is :  1.0
STD of the vector is :  1.0540925533894598
[0 1 0 0 1 0 3 4 3]
------------------------------------------------------------------------------------
Mean of the vector is :  1.3333333333333333
STD of the vector is :  1.49071198499986
[1 1 1 1 1 1 1 1 1]
------------------------------------------------------------------------------------
Mean of the vector is :  1.0
STD of the vector is :  0.0
[[-0.9486832980505138, -0.9486832980505138, 0.0, 0.9486832980505138, 0.9486832980505138, 1.8973665961010275, -0.9486832980505138, -0.9486832980505138, 0.0], [-0.8944271909999157, -0.22360679774997888, -0.8944271909999157, -0.8944271909999157, -0.22360679774997888, -0.8944271909999157, 1.1180339887498947, 1.7888543819998317, 1.1180339887498947], [nan, nan, nan, nan, nan, nan, nan, nan

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in double_scalars
  if sys.path[0] == '':


# Add X and Y here : 

In [56]:
x = np.array([[0,0,1],[0,1,1],[1,0,1],[2,0,1],[2,1,1],[3,0,1],[0,3,1],[0,4,1],[1,3,1]])

y = np.array([0,0,0,1,1,1,2,2,2])

In [40]:
x = np.array([[-1, -1], [1, -1], [-1, 1], [1, 1]])
y = np.array([0, 0, 0, 1])

In [85]:
x = np.array([[0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [0, 255, 255], [255, 0, 255], [255, 255, 255]])
y = np.array([0, 0, 0, 1, 0, 1, 1, 0])

NormVector =  np.array(normalize_Vector(x))

x = np.array(realNormalized(NormVector,x))

------------------------------------------------------------------------------------
[  0 255   0   0 255   0 255 255]
Mean of the vector is :  127.5
STD of the vector is :  127.5
------------------------------------------------------------------------------------
[  0   0 255   0 255 255   0 255]
Mean of the vector is :  127.5
STD of the vector is :  127.5
------------------------------------------------------------------------------------
[  0   0   0 255   0 255 255 255]
Mean of the vector is :  127.5
STD of the vector is :  127.5


# Preceptron Algorithm  

In [54]:
w_preceptron,s_preceptron = multiclass_perceptron(x,y,1,1)


----------------------------------------------------------------------------------------------------------
Itteration number : 1 at epoch :1
Xt is : [-1 -1]
Yt is : 1
Y-predected is the max out of this array :  [0. 0.]
Y-predected is :  1
Weights after this itteration :
[[0. 0.]
 [0. 0.]]
----------------------------------------------------------------------------------------------------------
Itteration number : 2 at epoch :1
Xt is : [ 1 -1]
Yt is : 1
Y-predected is the max out of this array :  [0. 0.]
Y-predected is :  1
Weights after this itteration :
[[0. 0.]
 [0. 0.]]
----------------------------------------------------------------------------------------------------------
Itteration number : 3 at epoch :1
Xt is : [-1  1]
Yt is : 1
Y-predected is the max out of this array :  [0. 0.]
Y-predected is :  1
Weights after this itteration :
[[0. 0.]
 [0. 0.]]
----------------------------------------------------------------------------------------------------------
Itteration number : 4 a

# SVM Algorithm 

In [55]:
w_SMV,s_SMV = multiclass_SVM(x,y,1,1)


----------------------------------------------------------------------------------------------------------
Itteration number : 1 at epoch :1
Xt is : [-1 -1]
Yt is : 1
all deltas to change Wt :
[1]
Wt new is :  [-1. -1.]
The delta of W 2 is :  0
Weights after this itteration :
[[-1. -1.]
 [ 0.  0.]]
----------------------------------------------------------------------------------------------------------
Itteration number : 2 at epoch :1
Xt is : [ 1 -1]
Yt is : 1
all deltas to change Wt :
[1]
Wt new is :  [ 0. -2.]
The delta of W 2 is :  0
Weights after this itteration :
[[ 0. -2.]
 [ 0.  0.]]
----------------------------------------------------------------------------------------------------------
Itteration number : 3 at epoch :1
Xt is : [-1  1]
Yt is : 1
all deltas to change Wt :
[1]
Wt new is :  [-1. -1.]
The delta of W 2 is :  1
Weights after this itteration :
[[-1. -1.]
 [ 1. -1.]]
----------------------------------------------------------------------------------------------------

# Multinomial logistic Regression Algorithm 

In [86]:
w_logisticR,s_logisticR = multiclass_multinomial_logisticR(x,y,1,1)


----------------------------------------------------------------------------------------------------------
Itteration number : 1 at epoch :1
Xt is : [-1. -1. -1.]
Yt is : 1
(Y predected) Value is : 0.5
(1 - Y predected) Value is : 0.5
this is w 1
grad =  [-0.5 -0.5 -0.5]
this is w 2
grad =  [0.5 0.5 0.5]
Weights after this itteration :
[[-0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5]]
----------------------------------------------------------------------------------------------------------
Itteration number : 2 at epoch :1
Xt is : [ 1. -1. -1.]
Yt is : 1
(Y predected) Value is : 0.731058578630005
(1 - Y predected) Value is : 0.268941421369995
this is w 1
grad =  [ 0.73105858 -0.73105858 -0.73105858]
this is w 2
grad =  [-0.26894142  0.26894142  0.26894142]
Weights after this itteration :
[[ 0.23105858 -1.23105858 -1.23105858]
 [ 0.23105858  0.76894142  0.76894142]]
----------------------------------------------------------------------------------------------------------
Itteration number : 3 at epo

# Global Thresholding

In [29]:
import cv2 as cv
import sys

def get_thresholds(histogram,n_th,margin=30):
    sorted_hist = sorted(histogram , reverse=True)
    thresholds  = [np.where(histogram == sorted_hist[0])[0][0]]
    for v in sorted_hist:
        if len(thresholds) >= n_th:
            break
        possible_th = np.where(histogram == v)[0][0]
        if np.abs(possible_th - thresholds[-1]) > margin :
            thresholds.append(possible_th)
    return thresholds

def update_thresholds(img, regions):
    thresholds = []
    for i in range(len(regions)-1):
        mask1 = regions[i]
        mask2 = regions[i+1]
        mu1 = np.mean(img[mask1])
        mu2 = np.mean(img[mask2])
        thresholds.append(np.mean([mu1, mu2]))
    return thresholds

def global_thresholding(img,n_th,margin=30,channel=0,mask=None, histSize = 256, histRange=[0,256]):
    try:
        histogram = cv.calcHist([img],[channel],mask,[histSize],histRange)
    except:
        histogram, _ = np.histogram(img, histSize, histRange)
    
    ths = get_thresholds(histogram,n_th,margin)
    print('Thresholds are : ', ths)
    delta = np.ones(n_th)
    e = sys.float_info.epsilon
    updated_ths = np.copy(ths)
    i=0
    while (np.linalg.norm(delta,1) > e):
        print('----------------------------------------------------------------------------------------------------------')
        print('epoch number : ',i)
        ths = np.copy(updated_ths)
        regions = []
        regions.append(img < ths[0])
        delta = np.zeros(n_th)
        if n_th > 1:
            for i in range(len(ths)-1):
                two_thresholds = sorted([ths[i+1],ths[i]])
                t1 = two_thresholds[0]
                t2 = two_thresholds[1]
                regions.append(np.logical_and(img<t1, img>t2))

        regions.append(img > ths[-1])
        print('The regions are : ')
        print(np.array(img[regions[0]]))
        print(np.array(img[regions[1]]))
        updated_ths = update_thresholds(img,regions)
        print('Updated Thresholds are : ', updated_ths)
        delta = np.array(updated_ths) - np.array(ths)
        i = i + 1
    return ths, regions



In [30]:
# # if image 

# img = cv.imread('imageName',0)
# histogram = cv.calcHist([img],[0],None,[256],[0,256])
# plt.plot(histogram)

# ths,regions = global_thresholding(img,1,30)
# segmented = apply_regions(img,regions)

In [31]:
x = [[146,125,140],[130,121,140],[110,105,125],[202,201,197],[160,144,144],
     [67,64,75],[19,18,23],[20,22,32],[20,21,26],[82,81,112],
     [148,124,96],[154,137,111],[181,168,136],[185,172,163],[114,87,60],
     [159,142,122],[163,138,107],[149,132,102],[169,155,129],[140,114,87]]

x = np.array(x)

y = np.array([1]*10 + [-1]*10)

test_x = np.array([[100,124,96],[154,100,111],[11,68,16],[85,72,53],[114,150,16]])

In [32]:
 means_x    = np.array([np.mean(ch) for ch in x])
 means_test = np.array([np.mean(ch) for ch in test_x])

In [33]:
x = [10,20,30,40,200,220,150,240,
      20,50,60,70,210,230,255,255,
      30,60,100,120,205,210,240,200,
      40,70,120,150,205,215,210,250
      ]

x = np.array(x)

y = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0,0,1,1,1,1,1])

In [34]:
ths, regions = global_thresholding(x,1,30)

Thresholds are :  [210]
----------------------------------------------------------------------------------------------------------
epoch number :  0
The regions are : 
[ 10  20  30  40 200 150  20  50  60  70  30  60 100 120 205 200  40  70
 120 150 205]
[220 240 230 255 255 240 215 250]
Updated Thresholds are :  [165.49107142857144]
----------------------------------------------------------------------------------------------------------
epoch number :  1
The regions are : 
[ 10  20  30  40 150  20  50  60  70  30  60 100 120  40  70 120 150]
[200 220 240 210 230 255 255 205 210 240 200 205 215 210 250]
Updated Thresholds are :  [145.02941176470588]
----------------------------------------------------------------------------------------------------------
epoch number :  2
The regions are : 
[ 10  20  30  40  20  50  60  70  30  60 100 120  40  70 120]
[200 220 150 240 210 230 255 255 205 210 240 200 150 205 215 210 250]
Updated Thresholds are :  [135.20588235294116]
------------------

In [35]:
means_test

array([106.66666667, 121.66666667,  31.66666667,  70.        ,
        93.33333333])